API/urls.py
from django.urls import path
from .api import *

urlpatterns = [
    path('list/', LeadListApi.as_view(), name='list-view'),
    path('list/<int:id>/', LeadDetailApi.as_view(), name='detail-view'),
    path('auth/', UserAuthentication.as_view(), name='auth-view'),

]

CRM2/urls.py
from django.contrib import admin
from django.urls import path, include
from leads import urls
import leads
import agents
import API
from API import urls
from agents import urls
from leads import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(API.urls)),

    path('leads/', include(leads.urls, namespace='leads')),
    path('agents/', include(agents.urls, namespace='agents')),

    path('', views.LandingPage.as_view(), name='landing-page'),
    path('login/', LoginView.as_view(), name='login-page'),
    path('logout/', LogoutView.as_view(), name='logout-page'),
    path('signup/', views.LeadSignUp.as_view(), name='signup-page'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('reset-password/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset-password-confirm/<uidb64>/<token>', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset-password-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from leads import views

app_name = 'leads'
urlpatterns = [
    path('', views.LeadList.as_view(), name='list-view'),
    path('<int:pk>/category', views.CategoryUpdateView.as_view(), name='category_update-view'),
    path('detail/<int:pk>/', views.LeadDetail.as_view(), name='detail-view'),
    path('create/', views.LeadCreate.as_view(), name='create-view'),
    path('update/<int:pk>/', views.LeadUpdate.as_view(), name='update-view'),
    path('delete/<int:pk>/', views.LeadDelete.as_view(), name='delete-view'),
    path('assign-agent/<int:pk>', views.AssignAgent.as_view(), name='assign_agent-view'),
    path('categories/', views.CategoryListView.as_view(), name='category_list-view'),
    path('categories/<int:pk>/', views.CategoryDetailView.as_view(), name='category_detail-view'),
]

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save, pre_save


class User(AbstractUser):
    is_organizer = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Lead(models.Model):
    SOURCE_CHOICES = (
        ('YouTube', 'YouTube'),
        ('Google', 'Google'),
    )
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    agent = models.ForeignKey("Agent", null=True, blank=True, on_delete=models.CASCADE)
    category = models.ForeignKey('Category', null=True, blank=True, on_delete=models.SET_NULL)
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField()
    def __str__(self):
        return self.first_name + " " + self.last_name


class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Category(models.Model):
    name = models.CharField(max_length=30)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    def __str__(self):
        return self.name


def post_user_created_signal(sender, instance, created, **kwargs):
    print(instance, created)
    if created:
        UserProfile.objects.create(user=instance)


post_save.connect(post_user_created_signal, sender=User)

leads/forms.py
from django import forms
from .models import Lead
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from .models import Agent

User = get_user_model()


class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = '__all__'


class LeadForm(forms.Form):
    first_name = forms.CharField(max_length=20)
    last_name = forms.CharField(max_length=20)
    age = forms.IntegerField(min_value=0)


class CustomUserCreation(UserCreationForm):
    class Meta:
        model = User
        fields = ('username',)
        field_classes = {'username': UsernameField}


class AssignAgentForm(forms.Form):
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request')
        agent = Agent.objects.filter(organization=request.user.userprofile)
        super(AssignAgentForm, self).__init__(*args, **kwargs)
        self.fields['agent'].queryset = agent


class CategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'category',
        )

leads/views.py
from django.shortcuts import render, redirect, reverse
from .models import Lead, Agent
from .forms import LeadForm, LeadModelForm, CustomUserCreation, AssignAgentForm, CategoryUpdateForm
from django.views.generic import *
from django.core.mail import send_mail
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from agents import mixins
from .models import Category


# Create your views here.

# CLASS BASED VIEWS


class LandingPage(TemplateView):
    template_name = 'landing.html'


class LeadList(LoginRequiredMixin, ListView):
    template_name = 'leads/list.html'

    def get_queryset(self):
        user = self.request.user
        if user.is_organizer:
            queryset = Lead.objects.filter(organization=user.userprofile, agent__isnull=False)
        else:
            queryset = Lead.objects.filter(organization=user.agent.organization, agent__isnull=False)
            queryset = queryset.filter(agent__user=user)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(LeadList, self).get_context_data(**kwargs)
        if self.request.user.is_organizer:
            queryset = Lead.objects.filter(organization=self.request.user.userprofile, agent__isnull=True)
            context.update({
                "unassigned_leads": queryset
            })
        return context


class LeadDetail(LoginRequiredMixin, DetailView):
    template_name = 'leads/detail.html'
    context_object_name = 'lead'

    def get_queryset(self):
        user = self.request.user
        if user.is_organizer:
            queryset = Lead.objects.filter(organization=user.userprofile)
        else:
            queryset = Lead.objects.filter(organization=user.agent.organization)
            queryset = queryset.filter(agent__user=user)
        return queryset


class LeadCreate(mixins.OrganisorAndLoginRequiredMixin, CreateView):
    template_name = 'leads/create.html'
    form_class = LeadModelForm

    def get_success_url(self):
        return reverse('leads:list-view')

    def form_valid(self, form):
        lead = form.save(commit=False)
        lead.organization = self.request.user.userprofile
        lead.save()
        send_mail(
            subject='A lead has been created',
            message="Go to the site to see the new lead",
            from_email='test@test.com',
            recipient_list=['test2@test.com'],
        )
        return super(LeadCreate, self).form_valid(form)


class LeadUpdate(mixins.OrganisorAndLoginRequiredMixin, UpdateView):
    template_name = 'leads/update.html'
    form_class = LeadModelForm

    def get_queryset(self):
        user = self.request.user
        return Lead.objects.filter(organization=user.userprofile)

    def get_success_url(self):
        return reverse('leads:list-view')


class LeadDelete(mixins.OrganisorAndLoginRequiredMixin, DeleteView):
    template_name = 'leads/delete.html'

    def get_queryset(self):
        user = self.request.user
        return Lead.objects.filter(organization=user.userprofile)

    def get_success_url(self):
        return reverse('leads:list-view')


class LeadSignUp(CreateView):
    template_name = 'registration/signup.html'
    form_class = CustomUserCreation

    def get_success_url(self):
        return reverse('login-page')


class AssignAgent(mixins.OrganisorAndLoginRequiredMixin, FormView):
    template_name = 'leads/assign_agent.html'
    form_class = AssignAgentForm

    def get_form_kwargs(self, **kwargs):
        kwargs = super(AssignAgent, self).get_form_kwargs(**kwargs)
        kwargs.update(
            {
                'request': self.request
            }
        )
        return kwargs

    def get_success_url(self):
        return reverse('leads:list-view')

    def form_valid(self, form):
        agent = form.cleaned_data['agent']
        lead = Lead.objects.get(id=self.kwargs['pk'])
        lead.agent = agent
        lead.save()
        return super(AssignAgent, self).form_valid(form)


class CategoryListView(LoginRequiredMixin, ListView):
    template_name = 'leads/category_list.html'
    context_object_name = 'category_list'

    def get_queryset(self):
        user = self.request.user
        if user.is_organizer:
            queryset = Category.objects.filter(organization=user.userprofile)
        else:
            queryset = Lead.objects.filter(organization=user.agent.organization)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        user = self.request.user
        if user.is_organizer:
            queryset = Lead.objects.filter(
                organization=user.userprofile
            )
        else:
            queryset = Lead.objects.filter(
                organization=user.agent.organization
            )
        context.update(
            {
                'unassigned_lead_count': queryset.filter(category__isnull=True).count()
            }
        )
        return context


class CategoryDetailView(LoginRequiredMixin, DetailView):
    template_name = 'leads/category_detail.html'
    context_object_name = 'category'

    def get_queryset(self):
        user = self.request.user

        if user.is_organizer:
            queryset = Category.objects.filter(
                organization=user.userprofile
            )
        else:
            queryset = Category.objects.filter(
                organization=user.agent.organization
            )
        return queryset


class CategoryUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'leads/category_update.html'
    context_object_name = 'lead'
    form_class = CategoryUpdateForm

    def get_queryset(self):
        user = self.request.user
        if user.is_organizer:
            queryset = Category.objects.filter(
                organization=user.userprofile
            )
        else:
            queryset = Category.objects.filter(
                organization=user.agent.organization
            )
        return queryset

    def get_success_url(self):
        return reverse('leads:detail-view', kwargs={'pk':self.get_object().id})


# FUNCTION BASED VIEWS
def landing_page(request):
    return render(request, 'landing.html')


def lead_list(request):
    leads = Lead.objects.all()
    context = {
        'leads': leads
    }
    return render(request, 'leads/list.html', context)


def lead_detail(request, pk):
    lead = Lead.objects.get(id=pk)
    context = {
        'lead': lead
    }
    return render(request, 'leads/detail.html', context)


def lead_create(request):
    form = LeadModelForm()
    if request.method == 'POST':
        form = LeadModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/leads')
    context = {
        'form': form,
    }
    return render(request, 'leads/create.html', context)


'''def lead_create(request):
    form = LeadModelForm()
    if request.method == 'POST':
        form = LeadModelForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            age = form.cleaned_data['age']
            agent = form.cleaned_data['agent']
            Lead.objects.create(
                first_name=first_name,
                last_name=last_name,
                age=age,
                agent=agent,
            )
            return redirect('/leads')
    context = {
        'form': form,
    }
    return render(request, 'leads/create.html', context)
'''


def lead_update(request, pk):
    lead = Lead.objects.get(id=pk)
    form = LeadModelForm(instance=lead)
    if request.method == "POST":
        form = LeadModelForm(request.POST, instance=lead)
        if form.is_valid():
            form.save()
            return redirect('/leads/')

    context = {
        'form': form,
        'lead': lead,
    }

    return render(request, 'leads/update.html', context)


def lead_delete(request, pk):
    lead = Lead.objects.get(id=pk)
    lead.delete()

    return redirect('/leads')

leads/templates/leads/assign_agent.html
{% extends 'base.html' %}

{% block content %}
<h1>Assign an agent to this lead</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="Submit">
    </form>
    <hr>
    <a href="{% url 'leads:list-view' %}">Main menu</a>
{% endblock %}

leads/templates/leads/category_detail.html
{% extends 'base.html'%}

{% block content %}

    <section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-20">
      <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">{{ category.name }}</h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
          These are the leads under this category</p>
    </div>
    <div class="lg:w-2/3 w-full mx-auto overflow-auto">
      <table class="table-auto w-full text-left whitespace-no-wrap">
        <thead>
          <tr>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">First Name</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Last Name</th>
          </tr>
        </thead>
        <tbody>
        {% for lead in category.lead_set.all%}
          <tr>
            <td class="px-4 py-3">
                <a href="{% url 'leads:detail-view' lead.pk %}">{{ lead.first_name }}</a></td>
            <td class="px-4 py-3">{{ lead.last_name }}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</section>

{% endblock content %}

leads/templates/leads/category_list.html
{% extends 'base.html'%}

{% block content %}

    <section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-20">
      <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Categories</h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
          These categories segment the leads</p>
    </div>
    <div class="lg:w-2/3 w-full mx-auto overflow-auto">
      <table class="table-auto w-full text-left whitespace-no-wrap">
        <thead>
          <tr>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Name</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Count</th>
          </tr>
        </thead>
        <tbody>
         <tr>
            <td class="px-4 py-3">Unassigned</td>
            <td class="px-4 py-3">{{ unassigned_lead_count }}</td>
          </tr>
        {% for category in category_list %}
          <tr>
            <td class="px-4 py-3">
                <a href="{% url 'leads:category_detail-view' category.pk %}">{{ category.name }}</a>
            </td>
            <td class="px-4 py-3">Count</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</section>

{% endblock content %}

leads/templates/leads/category_update.html
{% extends 'leads/list.html' %}
{% load tailwind_filters %}

{% block content %}

    <section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name }} {{ lead.last_name }}</h1>
        <div class="flex mb-4">
          <a href="{% url 'leads:detail-view' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
              Overview
          </a>
          <a href="{% url 'leads:category_update-view' lead.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
              Category
          </a>
          <a href="{% url 'leads:update-view' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
              Update Details
          </a>
        </div>
         <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy}}
            <input class="w-full bg-blue-500 hover:bg-blue-600 px-3 py-1 rounded-md" type="submit" value="Update">
          </form>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>

{% endblock content%}

leads/templates/leads/create.html
{% extends 'leads/list.html' %}
{% load tailwind_filters %}


{% block content %}
    <div class="max-w-lg mx-auto">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input class="w-full bg-blue-500 hover:bg-blue-600 px-3 py-1 rounded-md" type="submit" name="Submit">
    </form>
    <div class="py-5  border-t border-gray-200 mt-5">
         <a class="hover:text-blue-500" href="{% url 'leads:list-view' %}">Main menu</a>
    </div>
    </div>
{% endblock %}

leads/templates/leads/delete.html
{% extends 'leads/list.html' %}
{% load tailwind_filters %}
{% block content %}
    <div class="max-w-lg mx-auto">
        <div class="py-5  border-t border-gray-200">
            <h4>Are you sure to delete the lead?</h4>
        </div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p|crispy }}
            <input type="submit" value="Delete">
        </form>
        <a class="w-full bg-blue-500 hover:bg-blue-600 px-3 py-1 rounded-md" href="{% url 'leads:list-view' %}">Main menu</a>
    </div>
{% endblock %}

leads/templates/leads/detail.html
{% extends 'leads/list.html' %}

{% block content %}

    <section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name }} {{ lead.last_name }}</h1>
        <div class="flex mb-4">
          <a href="{% url 'leads:detail-view' lead.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Overview</a>
          <a href="{% url "leads:category_update-view" lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Category</a>
          <a href="{% url 'leads:update-view' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update Detail</a>
        </div>
        <p class="leading-relaxed mb-4">{{ lead.description }}</p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Age</span>
          <span class="ml-auto text-gray-900">{{ lead.age }}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Email</span>
          <span class="ml-auto text-gray-900">{{ lead.email }}</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Cell phone</span>
          <span class="ml-auto text-gray-900">{{ lead.phone_number }}</span>
        </div>
           <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Agent</span>
          <span class="ml-auto text-gray-900">{{ lead.agent.user.username }}</span>
        </div>
        </div>
  </div>
</section>
{% endblock content %}

leads/templates/leads/list.html
{%  extends 'base.html' %}

{% block content %}
    <section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
      <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
          <div>
              <h1 class="text-4xl text-gray-800">Leads</h1>
              <a href="{% url 'leads:category_list-view' %}">Category list</a>
          </div>
          {% if request.user.is_organizer %}
            <div>
              <a class="text-gray-500 hover:text-blue-500" href="{% url 'leads:create-view' %}">Create a new lead</a>
          </div>
          {% endif %}

      </div>
    <div class="flex flex-wrap -m-4">
        {% for lead in object_list %}
            <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{ lead.first_name}} {{ lead.last_name }}</h2>
            <p class="leading-relaxed text-base">{{ lead.description }}</p>
            <a href="{%  url 'leads:detail-view' lead.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">View this lead
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
        {% endfor %}
    </div>
  {% if unassigned_leads.exists %}
  <div class="flex flex-wrap -m-4">

  <div class="p-4 w-full">
      <h1 class="text-4xl text-gray-800">Unassigned leads</h1>
  </div>
        {% for lead in unassigned_leads %}
            <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{ lead.first_name}} {{ lead.last_name }}</h2>
            <p class="leading-relaxed text-base">{{ lead.description }}</p>
            <a href="{%  url 'leads:assign_agent-view' lead.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">Assign an agent
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
  </div>
  {% endif%}
  </div>
</section>
{% endblock content %}

leads/templates/leads/update.html
{% extends 'leads/list.html' %}
{% load tailwind_filters %}

{%  block content %}

       <section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name }} {{ lead.last_name }}</h1>
        <div class="flex mb-4">
          <a href="{% url 'leads:detail-view' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
              Overview
          </a>
          <a href="{% url 'leads:category_update-view' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
              Category
          </a>
          <a href="{% url 'leads:update-view' lead.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
              Update Details
          </a>
        </div>
         <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input  class="w-full bg-blue-500 hover:bg-blue-600 px-3 py-1 rounded-md" type="submit" value="Update">
          </form>
          <a href="{% url 'leads:delete-view' lead.pk %}" class="w-1/2 mt-3 flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Delete</a>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>
{% endblock content %}