API/urls.py
from django.urls import path
from .api import *

urlpatterns = [
    path('list/', LeadListApi.as_view(), name='list-view'),
    path('list/<int:id>/', LeadDetailApi.as_view(), name='detail-view'),
    path('auth/', UserAuthentication.as_view(), name='auth-view'),

]

CRM2/urls.py
from django.contrib import admin
from django.urls import path, include
from leads import urls
import leads
import agents
import API
from API import urls
from agents import urls
from leads import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(API.urls)),

    path('leads/', include(leads.urls, namespace='leads')),
    path('agents/', include(agents.urls, namespace='agents')),

    path('', views.LandingPage.as_view(), name='landing-page'),
    path('login/', LoginView.as_view(), name='login-page'),
    path('logout/', LogoutView.as_view(), name='logout-page'),
    path('signup/', views.LeadSignUp.as_view(), name='signup-page'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('reset-password/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset-password-confirm/<uidb64>/<token>', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset-password-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView


app_name = 'agents'
urlpatterns = [
  path('',AgentListView.as_view(), name = 'agent-list'),
  path('create', AgentCreateView.as_view(), name='agent-create'),
  path('detail/<int:pk>', AgentDetailView.as_view(), name='agent-detail'),
  path('update/<int:pk>', AgentUpdateView.as_view(), name='agent-update'),
  path('delete/<int:pk>', AgentDeleteView.as_view(), name='agent-delete'),

]

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CRM</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>

<body>
<div class='max-w-7xl mx-auto'></div>
{% include 'navbar.html' %}
{% block content %}

{% endblock content %}
</body>
</html>

templates/landing.html
{% extends 'base.html' %}

{% block content %}
<section class="text-gray-600 body-font">
  <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
    <div class="text-center lg:w-2/3 w-full">
      <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
          CRM built with DJANGO
      </h1>
      <p class="mb-8 leading-relaxed">
        This CRM helps you manage leads.
      </p>
      <div class="flex justify-center">
          <a class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg" href="{% url 'login-page' %}">Login to start</a>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/navbar.html
<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl">SVMR CRM</span>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">

         {% if not request.user.is_authenticated %}
        <a href="{% url 'signup-page' %}" class="mr-5 hover:text-gray-900">SignUp</a>
             {% else %}
        <a href="{% url 'leads:list-view' %}" class="mr-5 hover:text-gray-900">Leads</a>
             {% if request.user.is_organizer %}
        <a href="{% url 'agents:agent-list' %}" class="mr-5 hover:text-gray-900">Agents</a>
             {% endif %}
        {% endif %}
    </nav>
      {% if request.user.is_authenticated %}
          {% if request.user.is_agent %}
          User type: Agent
              {% elif request.user.is_organizer  %}
              User type: Organizer
          {% endif %}
      Logged in as : {{ request.user.username }}
          <a href="{% url 'logout-page' %}" class="ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
        Logout
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
      {% else %}
    <a href="{% url 'login-page' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
        Login
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
      {% endif %}
  </div>
</header>